plugins {
    id 'com.android.application'
}

android {
    namespace "com.xp.sim"
    compileSdk 34

    defaultConfig {
        applicationId "com.xp.sim"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
        }
    }
}

dependencies {
}
