name: XP-Sim Build
on:
  workflow_dispatch:

env:
  NDK_VERSION: "26.2.11394342"

jobs:
  build-android-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install NDK
        run: sdkmanager "ndk;${{ env.NDK_VERSION }}"

      - name: Pull SDL2 Source
        run: |
          chmod +x ./fetch_sdl.sh
          ./fetch_sdl.sh

      - name: Build Android APK
        run: |
          chmod +x ./build_android.sh
          ./build_android.sh

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: XP-Simulator-APK
          path: ./android/app/build/outputs/apk/release/app-release-unsigned.apk


  build-windows-exe:
    runs-on: windows-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Load MSVC Compiler
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install vcpkg & SDL2
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg install sdl2:x64-windows sdl2-image:x64-windows sdl2-ttf:x64-windows

      - name: CMake Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config Release

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: XP-Simulator-Win64
          path: build/Release/*.exe
